### ISSUE TITLE
Please publish last version to crates.io

### ISSUE THREAD

**Issue by jperelli** [astro/rust-osm-pbf-iter#6]
Hi, could you publish the latest code to crates.io?

This is because I was going to upload there a package I made that depends on yours, and crates won't let me use github as a source for the osm-pbf-iter dependency.

Thanks! and again awesome work!

**Comment by astro** [comment]
Happy to! Can we close your issues, or is there still something to be done?

**Comment by jperelli** [comment]
It's all working ok. Sorry for the mess of creating so many mixed issues, I'm a rust beginner and I was quite lost on that. So I think is ok to close both issues. The one in the pbf library (https://github.com/astro/rust-protobuf-iter/issues/1) I think it needs to be open because I think the issue is there with the signed ints. (as you said in this library that has no effect because it's impossible to have a negative index)
Thank you!

**Comment by astro** [comment]
0.2.0 released. Thank you for taking an interest.
